services:
  camunda:
    build: .
    container_name: camunda
    ports:
      - "18080:8080"
    environment:
      - DB_DRIVER=org.mariadb.jdbc.Driver
      - DB_URL=jdbc:mariadb://mariadb:3306/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - CAMUNDA_BPM_HISTORY_LEVEL=audit
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: camunda
      MARIADB_USER: camunda
      MARIADB_PASSWORD: camunda
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "13306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  mariadb-data:
